package main

var allowedCommands = map[string]bool{
	"ls":         true,
	"pwd":        true,
	"cat":        true,
	"curl":       true,
	"ping":       true,
	"nmap":       true,
	"while":      true,
	"echo":       true,
	"for":        true,
	"chmod":      true,
	"wget":       true,
	"arp":        true,
	"find":       true,
	"grep":       true,
	"head":       true,
	"tail":       true,
	"traceroute": true,
	"dig":        true,
	"nslookup":   true,
	"wc":         true,
	"whois":      true,
	"sort":       true,
	"uniq":       true,
	"netcat":     true,
	"telnet":     true,
	"nc":         true,
	"date":       true,
	"tree":       true,
	"sh":         true,
	"ip":         true,
	"jq":         true,
	"df":         true,
	"uptime":     true,
	"openssl":    true,
	"xargs":      true,
	"host":       true,
	// the following commands are not available
	// in owrap's docker image:
	"ffuf":      true,
	"subfinder": true,
	"httpx":     true,
	"terraform": true,
	"ansible":   true,
}
